### ISSUE TITLE
powerSpinner.setSelection()

### ISSUE THREAD

**Issue by brayann16** [skydoves/PowerSpinner#10]
**Please complete the following information:**
- Library Version 1.0.5
- Affected Device(s) A51 Android 10
 
I can't find the function setSelection to initialize the spinner to its default status as nothing was selected yet.
Thank you in advance

**Comment by skydoves** [comment]
Hi,
Do you mean this? [selectItemByIndex](https://github.com/skydoves/powerspinner#select-an-item-by-an-index)

**Comment by brayann16** [comment]
when I choose selectItemByIndex it crashes

**Comment by skydoves** [comment]
Oh, could you let me know the log of crashes?
Or you can reference this [demo code](https://github.com/skydoves/PowerSpinner/blob/master/app/src/main/java/com/skydoves/powerspinnerdemo/MainActivity.kt#L43).
