### ISSUE TITLE
unable to run the project

### ISSUE THREAD

**Issue by TheTechBee** [skydoves/PowerSpinner#106]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

I implemented the project in my android project using build gradle. when I add the code in the main activity xml it gives error on every line. please guide how to include the library,
**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, please read the [README](https://github.com/skydoves/PowerSpinner#including-in-your-project) file. It contains everything you need to build your project.

**Comment by TheTechBee** [comment]
after     implementation "com.github.skydoves:powerspinner:1.2.1" I am not able to do anything. activity xml is unable to recognise the following code.

<com.skydoves.powerspinner.PowerSpinnerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/white"
        android:gravity="center"
        android:hint="Question 1"
        android:padding="10dp"
        android:textColor="@color/white_93"
        android:textColorHint="@color/red"
        android:textSize="14.5sp"
        app:spinner_arrow_gravity="end"
        app:spinner_arrow_padding="8dp"
        app:spinner_divider_color="@color/white_70"
        app:spinner_divider_show="true"
        app:spinner_divider_size="0.4dp"
        app:spinner_item_array="@array/questions"
        app:spinner_item_height="46dp"
        app:spinner_popup_animation="dropdown"
        app:spinner_popup_background="@color/background800"
        app:spinner_popup_elevation="14dp" />

**Comment by skydoves** [comment]
Check out the few setups below has been done:
- Check out the dependency is added in your app module's `gradle.build`.
- The `mavenCentral()` repository has been added to your gradle.build and settings.gradle files.
- Sync the Gradle.

If you still can't configure the project, check out [the demo project](https://github.com/skydoves/PowerSpinner/tree/main/app). Thanks!
