### ISSUE TITLE
I don't want to use tint feature, means whaterver drawable I will give to arrow, it should show that only. 

### ISSUE THREAD

**Issue by gitam2869** [skydoves/PowerSpinner#113]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, could you please elaborate on this?

**Comment by gitam2869** [comment]
Actually I want replace traditional spinner icon with drawable, but when I used drawable it's showing in white only, means whole drawable becomes white. After some reading your code I found that you are giving color to drawable icon using **spinner_arrow_tint** due to that custom drawable becomes only with that color. 

The reason is that you are using tint for drawable which is default color is white

[https://github.com/skydoves/PowerSpinner/blob/main/powerspinner/src/main/kotlin/com/skydoves/powerspinner/PowerSpinnerView.kt](url)

Please check above url, in which on line number 565 you are setting color (tint) for drawable.

**Comment by skydoves** [comment]
Thanks for the details. This will be fixed on the next release.

**Comment by gitam2869** [comment]
Please do this asap. Thanks for your responsive reply.

**Comment by skydoves** [comment]
For now, you can available the fixed version on the `1.2.3-SNAPSHOT`. It will be released on the next stable. Thanks!

**Comment by gitam2869** [comment]
Okay, Thank you!

**Comment by skydoves** [comment]
New stable version 1.2.3 has been released. Thanks!
