### ISSUE TITLE
How i can scroll the spinner dialog?

### ISSUE THREAD

**Issue by osman-boy** [skydoves/PowerSpinner#114]
![Screenshot_20220527_120339](https://user-images.githubusercontent.com/77715479/170640128-45dc49ae-d27b-46cb-9e33-614892055ff7.png)

Don't scrollable

**Comment by skydoves** [comment]
Hi, could you specify the height size of the item height size?

**Comment by osman-boy** [comment]
I removed the height, app:spinner_item_height="40dp"
And everything worked! Thank you!

**Comment by skydoves** [comment]
No problem!
