### ISSUE TITLE
Highlight already selected item in the list

### ISSUE THREAD

**Issue by nikgupta1231** [skydoves/PowerSpinner#117]
**Is your feature request related to a problem?**

We need to show the user the last selection in the pop-up list.

**Describe the solution you'd like:**

there should be a way to mark bold or highlight the previous selected item in the pop-up item list

**Comment by skydoves** [comment]
Hi @nikgupta1231, sorry for the late response.
You can achieve this with the [Custom Spinner Adapter](https://github.com/skydoves/powerspinner#custom-spinner-adapter).
