### ISSUE TITLE
API to get persistent value 

### ISSUE THREAD

**Issue by eagskunst** [skydoves/PowerSpinner#12]
**Is your feature request related to a problem?**

There's no way of accessing a persistent value without looking at the library code and implementing it. 

**Describe the solution you'd like:**

A function to retrieve the value saved at a PowerSpinner by its String ID. Would be cool if it's static so it is not necessary to instance a PowerSpinner.

**Describe alternatives you've considered:**

Using a PreferenceFragment make the deal but it is difficult to style it (fonts specially).
Getting the SharedPreferences with the name of the package of the library works.

I could make a PR if the feature seems good for you :)

**Comment by skydoves** [comment]
Hi, @eagskunst Thank you for your issue :)
I was thinking the preference spec is not needed to be open (Public).
Because it stores and restores the selected position automatically.
And you can store the selected position manually via `OnSpinnerItemSelectedListener`.

**Comment by eagskunst** [comment]
The intention is to facilitate the integration with a custom settings layout, not using the PreferenceFragment/Activity provided by the SDK. But as you say, I ended up saving it on my local SharedPrefs and listening to item changes. I'll close the issue 👍
