### ISSUE TITLE
Support setting a foreground on the popupwindow item.

### ISSUE THREAD

**Issue by Legendami** [skydoves/PowerSpinner#123]
I'm able to set ?/selectableItemBackground when clicking the spinner, but not when clicking one of the items. I pretty much had this library implemented to the point where i was satisfied. But just by this single thing missing, i ended up creating my own listPopupWindow version.

**Comment by skydoves** [comment]
Hi @Legendami, you can achieve this by customizing the spinner with the [custom spinner adapter](https://github.com/skydoves/PowerSpinner#custom-spinner-adapter). If I have any plans for supporting this, let you know about this in the future. Thanks!
