### ISSUE TITLE
Require Kotlin 1.6 in java project

### ISSUE THREAD

**Issue by RachidLeLaborantin** [skydoves/PowerSpinner#124]
I use java in my project and i want to use your library but it requires Kotli 1.6 before to decompile the code. Thus, i am not able to use it
cause it don't appear in the problem. Any solution ?

Other thing, i want to use it in a preference

**Comment by skydoves** [comment]
Hey @RachidLeLaborantin, in this case, I highly recommend using version `1.2.2` or the lower version. Thanks!
