### ISSUE TITLE
Spinner arrow not showing any device

### ISSUE THREAD

**Issue by Vrajesh-StackApp** [skydoves/PowerSpinner#126]
Please complete the following information:

- Library Version - 1.2.3
- Affected Device - All

<com.skydoves.powerspinner.PowerSpinnerView
                            android:id="@+id/spinnerQuantity"
                            android:layout_width="@dimen/_40sdp"
                            android:layout_height="wrap_content"
                            android:layout_alignTop="@id/tvQuantity"
                            android:layout_alignBottom="@id/tvQuantity"
                            android:layout_marginStart="@dimen/_2sdp"
                            android:layout_toEndOf="@id/tvQuantity"
                            android:gravity="center"
                            android:fontFamily="@font/inter_regular"
                            android:textColor="@color/black"
                            android:textColorHint="@color/black"
                            android:textSize="14.5sp"
                            app:spinner_arrow_gravity="end"
                            app:spinner_arrow_animate="true"
                            app:spinner_arrow_padding="@dimen/_4sdp"
                            app:spinner_arrow_show="true"
                            app:spinner_arrow_tint="@color/red"
                            app:spinner_arrow_drawable="@drawable/ic_arrow_down"
                            app:spinner_divider_color="@color/text_bg"
                            app:spinner_divider_show="true"
                            app:spinner_divider_size="0.4dp"
                            app:spinner_item_height="46dp"
                            app:spinner_popup_animation="dropdown"
                            app:spinner_popup_background="@color/colorWhiteOpacity"
                            app:spinner_popup_elevation="14dp" />

**Comment by skydoves** [comment]
Thanks for reporting this issue! You can available it now in `1.2.4-SNAPSHOT`, and the fix will be included in the next stable release.

**Comment by skydoves** [comment]
`1.2.4` stable has been released. Thanks!
