### ISSUE TITLE
Spinner Arrow don't show

### ISSUE THREAD

**Issue by osman-boy** [skydoves/PowerSpinner#127]
### **When you use IconSpinnerItem the arrow is not displayed, why?**

_Device_ - Samsung A32
_os_ version - Android 12

<img src="https://user-images.githubusercontent.com/77715479/184098855-2544333d-9418-4373-830a-7eaeb1464abe.png" width="300" height="600" />
<img src="https://user-images.githubusercontent.com/77715479/184101213-947a1989-c75c-4012-9d25-74b596f4740e.jpg" width="300" height="600" />

**Comment by skydoves** [comment]
Thanks for reporting this issue! You can available it now in `1.2.4-SNAPSHOT`, and the fix will be included in the next stable release.

**Comment by skydoves** [comment]
`1.2.4` stable has been released. Thanks!
