### ISSUE TITLE
add spinner_popup_text_color Attributes

### ISSUE THREAD

**Issue by Geekince** [skydoves/PowerSpinner#131]
Controls the spinner popup item text color

**Comment by skydoves** [comment]
You can just change the text name with ` android:textColor="#25383C"` on your XML. Thanks!

**Comment by Luosoha** [comment]
@skydoves I believe he wants the text in the dropdown list to be different from the text color of the spinner (TextView) as I do.
Could this be added or we need to customize the adapter?

**Comment by skydoves** [comment]
@Luosoha For now, you can achieve it with the custom adapters.

**Comment by Luosoha** [comment]
> @Luosoha For now, you can achieve it with the custom adapters.

Aite thanks!
