### ISSUE TITLE
android:padding="10dp" is no effective

### ISSUE THREAD

**Issue by w1035412168** [skydoves/PowerSpinner#132]
<com.skydoves.powerspinner.PowerSpinnerView
                    android:id="@+id/sp_account"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:hint="@string/detail"
                    app:spinner_item_array="@array/account"
                    app:spinner_popup_background="@color/white"
                    app:spinner_divider_show="true"
                    app:spinner_item_height="50dp"
                    android:padding="10dp"
                    app:spinner_divider_color="@color/gray"
                    android:gravity="center_vertical"
                    android:layout_height="wrap_content"/>

This padding is invalid in the drop-down list. 
I remember it worked at first, and then I don't know when it stopped working, But it works in other projects

My gradle:
 defaultConfig {
        ...
        minSdk 21
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

**Comment by skydoves** [comment]
Hey @w1035412168, PowerSpinner does not support padding for the popup. You can achieve this with the custom adapter and with your own item layout for now. Thanks!

**Comment by w1035412168** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by w1035412168** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
