### ISSUE TITLE
class file for androidx.core.view.MenuHost not found

### ISSUE THREAD

**Issue by RiotGoesWoof** [skydoves/PowerSpinner#134]
**Please complete the following information:**
- Library Version: 1.2.4
- Affected Device(s) N/A (Cannot build)
 
**Describe the Bug:**

When adding the powerspinner implementation, I am able to sync gradle successfully and am able to access the classes/methods of PowerSpinner just fine.

As soon as I go to build though, I get a crash stemming from a "findViewById()" call in one of the auto-generated ViewBinding classes.  This is all the info Android Studio gives me:

```
> Task :pos:compileMataDebugJavaWithJavac
F:\Android Projects\project-title\build\generated\data_binding_base_class_source_out\Debug\out\com\someapp\databinding\ActivityMainBinding.java:476: error: cannot access MenuHost
      Toolbar toolbar = rootView.findViewById(id);
                                ^
  class file for androidx.core.view.MenuHost not found
1 error

> Task :pos:compileMataDebugJavaWithJavac FAILED
```

Doing a lot of digging, it seems to be something related to dependencies? But after playing around with it for a couple hours now I'm stumped. Has anyone else run into this before?

Edit: If I change the version to 1.1.9 it will start working. But anything 1.2.0 onward will give me the same error.

**Comment by skydoves** [comment]
Hey @RiotGoesWoof,
could you make sure that your project is currently using Appcompost version 1.4.1 and material 1.6.0?
Thanks!
