### ISSUE TITLE
Dismiss does not work in all cases

### ISSUE THREAD

**Issue by GerasimosGots** [skydoves/PowerSpinner#140]
**Please complete the following information:**
- Library Version v1.2.4
- Does not have to do with devices

**Describe the Bug:**

In cases where we have a fragment that uses a custom view e.g search bar, and that custom view has a recycler view
and in the adapter we use power spinner. If we have opened the spinner and then dismiss the custom view, as result the adapter will be destroyed but the power spinner cannot be dismissed and it's still visible.

**Expected Behavior:**

The power spinner should be dismissed when we destroy a view that contains the spinner.

**Comment by skydoves** [comment]
Hey @GerasimosGots, sorry for the late response. You should pass the view's lifecycle owner to the `setLifecycleOwner` method for this. If you still face the same issue with this solution, please re-open this issue. Thanks!
