### ISSUE TITLE
Can we give some top margin to spinner popup so that popup shows after some gap.

### ISSUE THREAD

**Issue by AzizFasihHazel** [skydoves/PowerSpinner#142]
Currently am showing spinner but the problem is spinner collapse with its popup. I want to give some top margin to popup so that it will show after spinner

**Comment by skydoves** [comment]
Hey @AzizFasihHazel, in the new release version 1.2.5, you can use the `spinner_popup_top_padding` attribute. Thanks!

**Comment by AzizFasihHazel** [comment]
Hi, thank you for your reply.
I want to give padding between the spinner and the drop down that contains
spinner items. This attribute ad space from top of drop down.
[image: Screenshot_20230227-145807.png]
