### ISSUE TITLE
Vertical ScrollBar not working

### ISSUE THREAD

**Issue by Gustavito271** [skydoves/PowerSpinner#143]
- Library Version: 1.2.4
- Affected Device(s): All Devices I tested

I tried to add a Scrollbar to the PowerSpinner, but it doesn't appear as it should. I tried to add on my own (didn't worked), then I tried to add as a person related in other issue (didn't worked as well). So, I'm trying to understanding what I'm doing wrong. Here's my code:

app:spinner_popup_max_height="250dp"
app:spinner_divider_show="false"
app:spinner_item_height="30dp"
app:spinner_popup_elevation="15dp"
android:scrollbarAlwaysDrawVerticalTrack="true"
android:scrollbars="vertical"
android:fadeScrollbars="false"
android:scrollbarThumbVertical="@color/verde_marcelo"
android:scrollbarSize="20dp"
android:scrollbarFadeDuration="0"
android:verticalScrollbarPosition="right"
android:scrollbarStyle="outsideInset"

**Comment by criscapadev85** [comment]
this is a giant shit until it works

**Comment by skydoves** [comment]
Hey @Gustavito271, @criscapadev85 sorry for the late response. You guys can customize the scrollbar by adding the code on your `styles.xml` file like the below:

```xml
  <style name="PowerSpinnerStyle">
    <item name="android:scrollbarAlwaysDrawVerticalTrack">true</item>
    <item name="android:scrollbars">vertical</item>
    <item name="android:fadeScrollbars">true</item>
    <item name="android:scrollbarThumbVertical">@drawable/powerspinner_scrollbar</item>
</style>
```

**Comment by skydoves** [comment]
I just added the guidelines on the README file: https://github.com/skydoves/PowerSpinner/blob/main/README.md#custom-scrollbar

Thanks for reporting this issue!
