### ISSUE TITLE
I want the popup menu to be able to appear above the spinner, like the dropDownVerticalOffset(-100dp) property, is there any way?

### ISSUE THREAD

**Issue by duonglkh** [skydoves/PowerSpinner#145]
I want the popup menu to be able to appear above the spinner, like the dropDownVerticalOffset(-100dp) property, is there any way?

**Comment by skydoves** [comment]
Hey @duonglkh, in the new version (1.2.5), you can use `getSpinnerHeight` function and give it to as a offset like the below:

```kotlin
powerSpinnerView.show(yOff = powerSpinnerView.getSpinnerHeight())
```

Thanks!
