### ISSUE TITLE
ScrollBar

### ISSUE THREAD

**Issue by Reksagon** [skydoves/PowerSpinner#148]
<com.skydoves.powerspinner.PowerSpinnerView
                android:id="@+id/spinner_city_send"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="20dp"
                android:layout_marginTop="10dp"
                android:layout_marginEnd="20dp"
                android:layout_marginBottom="10dp"
                android:background="@drawable/background_transfer_field"
                android:fontFamily="@font/gilroy_regular"
                android:gravity="center"
                android:hint="@string/hint_send_city"
                android:padding="10dp"
                android:textColor="#FFF"
                android:textColorHint="#80FFFFFF"
                android:textSize="16sp"
                android:maxHeight="100dp"
                android:fadeScrollbars="false"
                android:scrollbarFadeDuration="0"
                android:verticalScrollbarPosition="right"
                android:scrollbarThumbVertical="@android:color/black"
                android:scrollbarAlwaysDrawVerticalTrack="true"
                android:scrollbarSize="20dp"
                android:scrollbarStyle="outsideInset"
                android:scrollbars="vertical"
                mask:spinner_arrow_gravity="end"
                mask:spinner_arrow_padding="8dp"
                mask:spinner_item_height="46dp"
                mask:spinner_popup_animation="dropdown"
                mask:spinner_popup_elevation="14dp"
                tools:ignore="TouchTargetSizeCheck" />
                
       
![image](https://user-images.githubusercontent.com/71882300/222779812-a8053321-ce8a-41a2-8106-4d5cd879479c.png)

what am I doing wrong? why is the scrollbar not working?

**Comment by skydoves** [comment]
#143

**Comment by Reksagon** [comment]
this doesn't work either

Overriding @style/PowerSpinnerStyle which is marked as private in com.github.skydoves:powerspinner:1.2.4. If deliberate, use tools:override="true", otherwise pick a different name.

**Comment by Reksagon** [comment]
<style name="PowerSpinnerStyle" tools:override="true">
        <item name="android:scrollbarAlwaysDrawVerticalTrack">true</item>
        <item name="android:scrollbars">vertical</item>
        <item name="android:fadeScrollbars">false</item>
        <item name="android:scrollbarSize">2dp</item>
        <item name="android:scrollbarThumbVertical">@color/black</item>
    </style>

**Comment by skydoves** [comment]
Thanks for sharing the details! The `PowerSpinnerStyle` style will be marked as public in the next version.

**Comment by Reksagon** [comment]
When is the next version scheduled to be released?

**Comment by skydoves** [comment]
A new version 1.2.6 was released.
