### ISSUE TITLE
Dropdown items height change 2nd time

### ISSUE THREAD

**Issue by deepakbk1** [skydoves/PowerSpinner#15]
**Please complete the following information:**
- Library Version [e.g. v1.0.6]
- Affected Device(s) [e.g. Realme x2 with Android 10.0]
 
Items height change when again click on the spinner 

------------

Items height change should remain the same

**Comment by skydoves** [comment]
Hi,
It seems to recycle bugs since version `1.0.7`.
it is fixed on [1.0.9](https://github.com/skydoves/PowerSpinner/releases).
