### ISSUE TITLE
The arrow toggle on empty list

### ISSUE THREAD

**Issue by ShivamDev31** [skydoves/PowerSpinner#16]
**Please complete the following information:**
- Library Version [e.g. v1.0.7]
- Affected Device(s) [Any device]
 
**Describe the Bug:**

I've setup the spinner and the data has not been inflated in the spinner till now. So basically its an empty spinner till now. When I click on the spinner it toggles as per the implementation of `setOnClickListener()` in `PowerSpinnerView`. I tried to override `setOnClickListener()` but it did not work. So can you add a check in toggle() that it only toggles if list size > 0.

Something like this : if (adapter.getItems().isNotEmpty()) showOrDismiss() 
Need to add a getItems() in adapter classes which will return the list else can add a getSize() too which will return size only.

**Expected Behavior:**

It should not toggle the list, arrow should not animate.

**Comment by ShivamDev31** [comment]
@skydoves Shall I raise a PR for the same?

**Comment by skydoves** [comment]
It is released on the new version `1.0.8`.
