### ISSUE TITLE
Hello! I have mistake. Can you solve problem? Please 

### ISSUE THREAD

**Issue by Madiyar5404** [skydoves/PowerSpinner#162]
Cannot access 'androidx.lifecycle.FullLifecycleObserver' which is a supertype of 'com.skydoves.powerspinner.PowerSpinnerView'. Check your module classpath for missing or conflicting dependencies 
![image](https://github.com/skydoves/PowerSpinner/assets/124025514/70fee785-3e40-48c7-83a6-7f50942a18a8)

**Comment by Madiyar5404** [comment]
https://github.com/skydoves/PowerSpinner/issues/159        As you said, I fulfilled all these conditions.

**Comment by KruBakhal** [comment]
Yes, i also face this issue.

**Comment by skydoves** [comment]
Hey guys, what `androidx.lifecycle` version do you use? I'd prefer using 2.6.1 or higher.
