### ISSUE TITLE
com.google.android.material.textview.MaterialTextView cannot be cast to com.skydoves.powerspinner.PowerSpinnerView

### ISSUE THREAD

**Issue by IZLAm90** [skydoves/PowerSpinner#165]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by IZLAm90** [comment]
Library Version [e.g. v1.2.4]
while i try to open the layout and get the view by viewbinding i have this problem
       java.lang.ClassCastException: com.google.android.material.textview.MaterialTextView cannot be cast to com.skydoves.powerspinner.PowerSpinnerView

**Comment by skydoves** [comment]
Dup #166
