### ISSUE TITLE
Debounce OnSpinnerOutsideTouchListener and onClickListener 

### ISSUE THREAD

**Issue by skydoves** [skydoves/PowerSpinner#17]
#11

**Comment by skydoves** [comment]
Released in the new version `1.0,8`.

**Comment by hulkthetyagi** [comment]
on out side touch, Popup window does not debounce itself

**Comment by skydoves** [comment]
Hi, @hulkthetyagi 
For resolving this issue, use this method.

```kotlin
spinnerView.setIsFocusable(true)
```
And you can reference the usage in the [demo](https://github.com/skydoves/PowerSpinner/tree/master/app) project.
Thanks!
