### ISSUE TITLE
Request: improve animation when opening/closing 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [skydoves/PowerSpinner#2]
**Is your feature request related to a problem?**
Seems in the sample animations that it scales the list in animation, so the items look squeezed :

https://i.imgur.com/R8wPZXW.png

**Describe the solution you'd like:**
 On the native one, it doesn't scale, so it shows nicely (play in super slow motion) :

https://www.youtube.com/watch?v=on_OrrX7Nw4

**Describe alternatives you've considered:**
Use native one?

**Comment by skydoves** [comment]
@AndroidDeveloperLB 
Hi,
I already noticed it and I resolved it via fading effect instead of scale down.

After:
https://user-images.githubusercontent.com/24237865/71558150-3cfd1700-2a93-11ea-9809-ce33309ebc96.gif

Thank you for your issue and interest! :)

**Comment by AndroidDeveloperLB** [comment]
I don't see it fixed on your gif animation:

![image](https://user-images.githubusercontent.com/5357526/71886942-bb1d8580-3145-11ea-944d-cbc2a4edb716.png)

**Comment by skydoves** [comment]
@AndroidDeveloperLB 

Ah, I thought you meant items being squeezed when it is disappearing.
I was thinking the scaling animation makes more dynamically the popup but it could seem weird in some cases.
I will add `Normal` type of [SpinnerAnimation](I was thinking the scaling animation makes more dynamically the popup but it could seem weird in some cases.).
Thank you!

**Comment by AndroidDeveloperLB** [comment]
I'm talking about both appearing and disappearing.
Can you please have the same animation as on the native spinner?
I don't think it's scale animation. If you look at the video, you will see that all texts are shown well and not stretched while animating.

**Comment by skydoves** [comment]
@AndroidDeveloperLB 
Yes.
I just added a normal type.
https://user-images.githubusercontent.com/24237865/71888721-14a4a500-3184-11ea-9d47-a744229577f2.gif

It is released on version `1.0.3`.

**Comment by AndroidDeveloperLB** [comment]
I think it's nicer.

**Comment by AndroidDeveloperLB** [comment]
I suggest to update the animations of the repository, and make this the default animation .

**Comment by skydoves** [comment]
@AndroidDeveloperLB 
Hi, the `NORMAL` type animation is already the default animation after the lastest version `1.0.3'.
You can reference here: [Arrbitues](https://github.com/skydoves/powerspinner#powerspinnerview-attributes).

**Comment by AndroidDeveloperLB** [comment]
So I suggest to update the main page of the repository then. :)

**Comment by skydoves** [comment]
Hi, it's updated. 

https://user-images.githubusercontent.com/24237865/71962685-534a6600-323d-11ea-9e1e-df1f68cb2181.gif

I changed the first preview. 👍

**Comment by AndroidDeveloperLB** [comment]
I still see it for the second and third :
https://github.com/skydoves/PowerSpinner
