### ISSUE TITLE
On Scrolling down . The listing order changes

### ISSUE THREAD

**Issue by rulfox** [skydoves/PowerSpinner#20]
- Library Version [1.0.8]
- Affected Device(s) Realme X2 Pro with Android 10]
 
I have a list of objects in which each object indicate Year
Its like 1970 - 2020
I have created custom adapter.
On clicking the spinner, the list is displayed from 1970 to 1980
On scrolling down, the year displaying is random

**Comment by mjalili27** [comment]
use version 1.06

**Comment by skydoves** [comment]
Hi, thanks for submitting this issue.
This will be fixed in the next version.

**Comment by skydoves** [comment]
Released a new version [1.0.9](https://github.com/skydoves/PowerSpinner/releases/tag/1.0.9).
Thank you for your issue :)
