### ISSUE TITLE
Example for custom adapter

### ISSUE THREAD

**Issue by 100nandoo** [skydoves/PowerSpinner#22]
Hi, would you kindly provide example for custom adapter. Currently I manage to implement using custom adapter. Everything work except the on click listener not working. Thanks

**Comment by skydoves** [comment]
Hi, here is the example for a custom adapter.
[IconSpinnerAdapter](https://github.com/skydoves/PowerSpinner/blob/master/powerspinner/src/main/java/com/skydoves/powerspinner/IconSpinnerAdapter.kt) basically provided by library level.
