### ISSUE TITLE
pop item wrap width

### ISSUE THREAD

**Issue by NemoChen317** [skydoves/PowerSpinner#24]
how can i user wrap_content to pop item width?
when i dynamic set spinner items

thank you

**Comment by skydoves** [comment]
Hi, the width size of the popup follows the width size of `PowerSpinnerView` or the `spinnerPopupWidth` attribute. Could you let me know about some usage examples of `wrap_content`?

**Comment by NemoChen317** [comment]
> Hi, the width size of the popup follows the width size of `PowerSpinnerView` or the `spinnerPopupWidth` attribute. Could you let me know about some usage examples of `wrap_content`?

Hi, because my PowerSpinnerView use wrap_content and show normal ! but spinner popup text will cut some char not show all . and the width not same with PowerSpinnerView.

thank you

**Comment by skydoves** [comment]
Hi, @NemoChen317, sorry for the late reply.
I will include this issue in the next release.
Thank you for your issue :)

**Comment by skydoves** [comment]
It is released in the new version `1.1.0`!
Thank you for your issue :)
