### ISSUE TITLE
unable to disable OverScrollMode

### ISSUE THREAD

**Issue by Prakash19921206** [skydoves/PowerSpinner#25]
**Please complete the following information:**
- Library Version [e.g. v1.0.9]
- Affected Device(s) [ Asus Zenphone , android 9]
 
**Describe the Bug:**
i'm using custom adapter 
`class my_adapter extends RecyclerView.Adapter implements PowerSpinnerInterface`

i tried setting `powerSpinnersetOverScrollMode(View.OVER_SCROLL_NEVER)`
still i see the overScroll effect at top and bottom of list

**Expected Behavior:**
OverScroll effect should be hidden

**Comment by skydoves** [comment]
Use below methods
```kotlin
spinnerView.getSpinnerRecyclerView().overScrollMode = View.OVER_SCROLL_NEVER
spinnerView.getSpinnerRecyclerView().setFadingEdgeLength(0)
```

**Comment by Prakash19921206** [comment]
below line(in Java) worked. Thanks

`spinnerView.getSpinnerRecyclerView().setOverScrollMode(View.OVER_SCROLL_NEVER);`
