### ISSUE TITLE
Load Icons From Url

### ISSUE THREAD

**Issue by HoseinHaqiqian** [skydoves/PowerSpinner#26]
is there any way to load icons from url?

**Comment by skydoves** [comment]
Hi, In fact, `IconSpinnerAdapter` is an example of a custom adapter.
So in this case, you can implement a custom adapter using third party image loading libraries like Glide/Picasso/Fresco/Coil by reference  `IconSpinnerAdapter`.

**Comment by abhishektiwari-obsidiam** [comment]
Hi @skydoves 
Even if we do that, the main view which is shown after item selection extends TextView and setting image from url on TextView as a drawable is pain.
Please help us out.
