### ISSUE TITLE
dynamic add powerSpinner in recycleview item

### ISSUE THREAD

**Issue by NemoChen317** [skydoves/PowerSpinner#27]
hello

when I use recycle view to dynamic add powerSpinner item row
i found some bug

1. when i add spinner item and notifyDataSetChanged recycleview
    the spinner popup window will show match cellphone screen width , but my spinner' width not match cellphone screen
我的每一條row 都有兩個 spinner ， 每當我新增並且更新
點擊spinner 跳出的 popup window 會跟螢幕寬一樣 ，但是我的spinner 只有3分之二 螢幕的寬度而已

2. when i add Multiple spinner item row in recycleview and notifyItemInserted
    touch some spinner's popup window not show
當我一次新增多個row 並且新增一次就notifyItemInserted 更新！ 
當我點擊比較下面的spinner 之後，他的popup window 並不會show ， 但是 arrow 是有在轉的

3. when i scroll recycle view , the spinner select listener will call and position not current
當我有多個spinner row 當我滑動recycleview時  spinner的select listener 會觸發
並且裡面的position 會亂跳！ 導致 不會所選的position 

thank for all
以上 感謝

**Comment by skydoves** [comment]
Hi, @NemoChen317! Sorry for the late reply.
You can access the `RecyclerView` using below way, but I don't recommend like this way.
```kotlin
val adapter = spinnerView1.getSpinnerRecyclerView().adapter as DefaultSpinnerAdapter
adapter.setItems(myItemList)
adapter.notifyDataSetChanged()
```
