### ISSUE TITLE
item layout order

### ISSUE THREAD

**Issue by Meglali20** [skydoves/PowerSpinner#28]
Hi,
Great spinner! I would like to change something, I want to put the text below the image is there a way to that?

**Comment by skydoves** [comment]
Hi @Meglali20,
You can create a [custom adapter](https://github.com/skydoves/powerspinner#customized-adapter-1) using your own customized layout style.
The [IconSpinnerAdapter](https://github.com/skydoves/PowerSpinner/blob/master/powerspinner/src/main/java/com/skydoves/powerspinner/IconSpinnerAdapter.kt) is one of the customized adapters provided in this library.

**Comment by Meglali20** [comment]
> Hi @Meglali20,
> You can create a [custom adapter](https://github.com/skydoves/powerspinner#customized-adapter-1) using your own customized layout style.
> The [IconSpinnerAdapter](https://github.com/skydoves/PowerSpinner/blob/master/powerspinner/src/main/java/com/skydoves/powerspinner/IconSpinnerAdapter.kt) is one of the customized adapters provided in this library.

Thank you for your answer. I am using java, I added a custom adapter the problem is with this 
override fun notifyItemSelected(index: Int) {
  this.spinnerView.notifyItemSelected(index, this.spinnerItems[index].text)
  this.onSpinnerItemSelectedListener?.onItemSelected(index, this.spinnerItems[index])
}

    @NotNull
    @Override
    public PowerSpinnerView getSpinnerView() {
        return null;
    }

it returns a null and must be NonNull where should I assign the PowerSpinnerView it should return?

**Comment by skydoves** [comment]
As you can see the `IconAdapter`, You can hand over `PwerSpinnerView` via the constructor.
Also when implementing your custom adapter, you should define `PowerSpinnerView` field in your class and it can be used for applying attributes on your own ViewHolder. The `PowerSpinnerView` has many kinds of attributes including text color, typeface, text size, padding or etc from XML layout. And they might be used in your custom adapter.

**Comment by Meglali20** [comment]
@skydoves but where to assign the value of powerSpinnerView?

**Comment by skydoves** [comment]
For writing an example of the `IconSpinnerAdapter`:
```java
IconSpinnerAdapter adapter = new IconSpinnerAdapter(myPowerSpinnerView);
```
Add a new constructor to your custom adapter.

**Comment by skydoves** [comment]
Here is an example codes using `IconSpinnerItem` written Java.
```java
class CustomAdapter extends RecyclerView.Adapter<CustomAdapter.CustomViewHolder>
  implements PowerSpinnerInterface<IconSpinnerItem> {

  private PowerSpinnerView powerSpinnerView;

  public CustomAdapter(PowerSpinnerView powerSpinnerView) {
    this.powerSpinnerView = powerSpinnerView;
  }

  @NotNull @Override public PowerSpinnerView getSpinnerView() {
    return powerSpinnerView;
  }
```

**Comment by Meglali20** [comment]
Thank you, I got this part, but when calling 
notifyItemSelected(i, String.valueOf(i)); 
it will only set the text for the powerSpinnerView not display the image or the full item

**Comment by Meglali20** [comment]
@skydoves  
I figured it out from the IconSpinnerAdapter.kt class, thank you for your help!
