### ISSUE TITLE
if spinner is open and back clicked the spinner remains open and does not destroy

### ISSUE THREAD

**Issue by mjalili27** [skydoves/PowerSpinner#30]
**Please complete the following information:**
- Library Version [e.g. v1.0.9]
- Affected Device(s) [e.g. Pixel 2 with Android 9.0]
 
**Describe the Bug:**

if the spinner is open in a fragment and you back click, the spinner remains open and does not destroy this happens when I was using fragments I did not test in activities

**Expected Behavior:**

close spinner when fragment is poped and closed

**Comment by skydoves** [comment]
Hi, @mjalili27!
Thank you for your issue :)
Unfortunately, the spinner can not listen to the back key.
Because the spinner popup uses a popup window, but the basic Android SDK doesn't support it now.
Instead, you can use `setLifecycleOwner` and we can listen to the lifecycle is destroyed.
