### ISSUE TITLE
Arrow color is not changeable on Android 6 device

### ISSUE THREAD

**Issue by mikebikemusic** [skydoves/PowerSpinner#31]
- Library Version 1.0.9
- Affected Device(s) [e.g. alps 06 with Android 6.0
 
**Describe the Bug:**
       
android:textColor="@color/colorDarkGreen"
android:background="@color/offWhite"    (#eeeeee)
app:spinner_arrow_tint="@color/colorDarkGreen" (#00574B)

Arrow always shows white on older Android version. Even if I change spinner_arrow_tint to #000000

![device-2020-07-18-104222](https://user-images.githubusercontent.com/4509918/87858562-9d468f80-c8e3-11ea-99ff-3462e524580c.png)

**Expected Behavior:**

Arrow color should be the same color as the text color, since both are set to the same value.
Arrow color is changeable on simulator and on Samsung A10.

**Comment by skydoves** [comment]
Hi, @mikebikemusic!
I just updated the demo project code about the changing tint color of the arrow.
But I can't found any devices that happened that issue.
Could please you run the [demo project](https://github.com/skydoves/PowerSpinner/tree/master/app) on your device?
Thank you for your issue!

**Comment by mikebikemusic** [comment]
In the demo project, I see the arrow color is now yellow, so that works. But now I see two differences: 

First of all, the emulator shows that you only changed the arrow for the first spinner, which looks correct. But on the Android 6 device, all 3 spinners turn yellow.

A side effect is that when I choose yellow in the second spinner on the Android 6 device, the arrow disappears:

![device-2020-07-19-072308](https://user-images.githubusercontent.com/4509918/87877477-7fd0fe80-c993-11ea-9d02-2447c1850f2c.png)

I suspect the change you made is good enough for me since I'm not currently planning using more than one spinner. Thank you for your quick response.

Mike

**Comment by mikebikemusic** [comment]
I found that explicitly setting the spinner_arrow_tint to white_70 on the other two demo spinners is a workaround for Android 6.

**Comment by skydoves** [comment]
Thank you for your details!
Then the problem will be fixed If I change the default color of the arrow to the explicit color like `white`.
This resolve will be included in the next version.
Thank you for your issue :)

**Comment by mikebikemusic** [comment]
That sounds perfect. Thank you again.

**Comment by skydoves** [comment]
It is released a new version [1.1.0](https://github.com/skydoves/PowerSpinner/releases/tag/1.1.0).
Thank you for your issue contribution and a coffee! ❤️

**Comment by mikebikemusic** [comment]
Confirming fixed in my app with 1.1.0
