### ISSUE TITLE
how to change Itemheight? I can only change total height but the items are still on the top. 

### ISSUE THREAD

**Issue by moo611** [skydoves/PowerSpinner#34]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
Hi, @moo611
Sorry for the late reply.
You can set a customized height in your customized layout.
You can reference how to create [customized adapter](https://github.com/skydoves/powerspinner#customized-adapter).

**Comment by moo611** [comment]
thanks,solved
