### ISSUE TITLE
Get selected Item

### ISSUE THREAD

**Issue by MiguelAlvesMiguel** [skydoves/PowerSpinner#37]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
Hi,
You can get the index of selected item using `powerSpinnerView.selectedindex`.
And you already having the item list of the adapter when you initialzing it.

**Comment by MiguelAlvesMiguel** [comment]
> Hi,
> You can get the index of a selected item using `powerSpinnerView.selectedindex`.
> And you have the item list of the adapter when you initializing it.

I was talking about getting the selected item, not the index, but figured out you can just use .getText() with no problems
