### ISSUE TITLE
Feature to support difference between spinner and popup

### ISSUE THREAD

**Issue by MJ1998** [skydoves/PowerSpinner#39]
**Is your feature request related to a problem?**
Yes.

A clear and concise description of what the problem is.
Basically I need to set a border color only to the spinner. So after adding the border background, the popup is so close that it hides the bottom border.

**Describe the solution you'd like:**
Feature to support difference between spinner and popup

An attribute that supports this difference.

**Describe alternatives you've considered:**
Tried appending PowerSpinner xml to Relative layout ad setting background of the relative layout only. Same problem.

A clear description of any alternative solutions you've considered.
<RelativeLayout
lh..
lw..
background="@drawable/border"
..>
<PowerSpinner
..
/>
</RelativeLayout>

**Comment by skydoves** [comment]
Hi @MJ1998, sorry for the late reply.
It is released a new version [1.1.4](https://github.com/skydoves/PowerSpinner/releases/tag/1.1.4).

We can resolve this issue using a `yOff` attribute on `show()` or `showOrDismiss()` function.
```kotlin
powerSpinnerView.setOnClickListener {
  powerSpinnerView.showOrDismiss(xOff = 0, yOff = 30) // 30 px offset from the spinnerView.
}
```

**Comment by jakoss** [comment]
I have the same issue as OP, the provided solution does not work well:
![image](https://user-images.githubusercontent.com/3933348/95568345-65ec0880-0a24-11eb-8888-1e52489c99ef.png)

As you can see - bottom border disappeared anyway, and popup is strangely low

**Comment by skydoves** [comment]
@jakoss 
Give the border for all edges with small `yOff`.

The result:
![KakaoTalk_20201129_133837371](https://user-images.githubusercontent.com/24237865/100533489-59c44080-3248-11eb-8c99-11b84a7d7116.jpg)
