### ISSUE TITLE
Access to `binding.body` 

### ISSUE THREAD

**Issue by fturek** [skydoves/PowerSpinner#41]
**Is your feature request related to a problem?**

I have the list inside the item of the spinnerRecyclerView. I want to recalculate body height when a list is visible.

**Describe the solution you'd like:**

Additinonal public method:

`fun getSpinnerBody(): RecyclerView = binding.body`

**Comment by skydoves** [comment]
Hi, you can use the below method.
```kotlin
spinnerView.getSpinnerRecyclerView()
```

**Comment by fturek** [comment]
Hi!

Sorry, I meant LinearLayout which has RecyclerView.

**Comment by fturek** [comment]
I was trying to recalculate the height of the RecyclerView, but unfortunately it doesn't work. I believe that the body limits the recycler view. But I'm not able to get access to that property.

**Comment by skydoves** [comment]
Ah, is it related to a resizing issue when using `setItems` different items size?

**Comment by fturek** [comment]
Well, not exactly. I build my own adapter. Each item of that recyclerView has its own list, and that list is collapsed at the beginning. When I click on that item I want to expand the item's list. It works great, but the body where the "main" recyclerView is is fixed, and it doesn't adapt to new recyclerView height. 
To see other elements, I have to scroll through the list. I want to recalculate the height of the body to avoid scrolling.

**Comment by skydoves** [comment]
Hi, @fturek 
It is released a new version [1.1.5](https://github.com/skydoves/PowerSpinner/releases/tag/1.1.5).
The `getSpinnerViewBody()` method is added, but the popup height size will be changed if you change your own adapters. 
Thank you for your issue!

**Comment by fturek** [comment]
Hi!

Thank you for your help! Looks great! 👍 

So based on what you said - isn't that possible to change the popup height by my own whenever I want? 

If not - is that possible to add an option to get the `spinnerWindow: PopupWindow`? Maybe it will solve my problem.
Sorry that I didn't mention it in previous issue - I didn't catch earlier that this property has `private` modifier.

**Comment by skydoves** [comment]
You can change the height in two ways.

1. Use  `setSpinnerPopupHeight()` or `spinner_popup_height` in XML.
2. Just change the recyclerView height using the `getSpinnerRecyclerView()`. This works in version 1.1.5.

**Comment by fturek** [comment]
Ok, I see.

And what about changing ht  height at the runtime? Setting it by _getSpinnerRecyclerView()_ doesn't work in my case.

**Comment by skydoves** [comment]
@fturek 
You can change it at the runtime like below.

```kotlin
spinnerView.spinnerPopupHeight = 300
```
