### ISSUE TITLE
How to set "bold" style to spinner title, but for popup items not bold (usual) style?

### ISSUE THREAD

**Issue by Pirokar** [skydoves/PowerSpinner#43]

**Comment by skydoves** [comment]
Try the below codes.
```kotlin
<com.skydoves.powerspinner.PowerSpinnerView
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:textStyle="bold"
```

**Comment by Pirokar** [comment]
@skydoves this will makes text in popup bold too. But I need only bold only for title, whan spinner is closed.

**Comment by skydoves** [comment]
Ah, I understood. 
There is the only way to implement it is by using a custom adapter now.
I will consider adding an attribute related to it.
Thanks!

**Comment by skydoves** [comment]
Hi, @Pirokar 
The new version [1.1.6](https://github.com/skydoves/PowerSpinner/releases/tag/1.1.6) has been released.
If you use [IconSpinnerAdapter](https://github.com/skydoves/powerspinner#iconspinneradapter), you can change each items' text style (Typeface).

```kotlin
  val text: CharSequence,
  val icon: Drawable? = null,
  @DrawableRes val iconRes: Int? = null,
  @Px val iconPadding: Int? = null,
  val iconGravity: Int = Gravity.START,
  val typeface: Int? = null,
  val gravity: Int? = null,
  val textSize: Float? = null,
  @ColorInt val textColor: Int? = null,
```
Thanks for your issue!
