### ISSUE TITLE
Popup is not visible when the PowerSpinner is located at the bottom of a layout

### ISSUE THREAD

**Issue by mitchgrogg** [skydoves/PowerSpinner#44]
**Please complete the following information:**
- Library Version [v1.1.5]
- Affected Device(s) [Google Pixel 3a]
 
**Describe the Bug:**

If the PowerSpinner is at the bottom of a layout, the popup is not visible. Or if it is near the bottom of a layout only one or two entries are visible.

**Expected Behavior:**

The popup should be shown above the PowerSpinner if the view is located in the bottom half of the layout.

**Comment by Kanval87** [comment]
@skydoves Hi, do we have any update on this issue ?

**Comment by ashwani205** [comment]
@skydoves Hi, Any update regarding this issue?

**Comment by skydoves** [comment]
Sorry for the late response. 
Make sure you have set the specific size of the popup with the `spinner_popup_height` attribute or `spinnerPopupHeight` property of the `PowerSpinnerView`.
Thanks!
