### ISSUE TITLE
- Library version is 1.1.5.

### ISSUE THREAD

**Issue by Liu1023210** [skydoves/PowerSpinner#45]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Please explain about your details and reopen this issue ;)
