### ISSUE TITLE
popup dismiss

### ISSUE THREAD

**Issue by hulkthetyagi** [skydoves/PowerSpinner#46]
- Library Version [1.1.6]
- Affected Device(s) [e.g. Vivo V15pro with Android 10]
 
**Description of the Bug:**
    When adding two or more powerspinner,.
    we select spinner first it shows popup window and then we select spinner second it shows popup window without dismissing the previous popup window.

**Expected Behavior:**

   It should dismiss previous opened popup window and then show the newly selected or clicked spinner.

**Comment by skydoves** [comment]
Hi,
Try to use below method.
```kotlin
spinner.setIsFocusable(true)
```

**Comment by hulkthetyagi** [comment]
Thanks...
Solved the issue.
