### ISSUE TITLE
How can I use a field of an object as data source?

### ISSUE THREAD

**Issue by nocrisis** [skydoves/PowerSpinner#47]
such as spinner.setItems(List<T> obj),but  just show obj.field in spinner

**Comment by skydoves** [comment]
Hi, could you explain more details?
And you can get the selected field via `OnSpinnerItemSelectedListener`.
```kotlin
setOnSpinnerItemSelectedListener<String> { oldIndex, oldItem, newIndex, newText ->
   toast("$text selected!")
}
```

**Comment by nocrisis** [comment]
Could the T type of method params setItems(List<T> objs) be a javabean in addition to a String?Then use a String type field of the javaBean as item?

**Comment by skydoves** [comment]
Of course, you can use your custom type, but you should create your own adapter. Reference this [custom adapter](https://github.com/skydoves/powerspinner#customized-adapter).
If you use not your customized adapter, the default adapter receives a String type which is the most used generally.
