### ISSUE TITLE
setOnSpinnerOutsideTouchListener does not work (Java)

### ISSUE THREAD

**Issue by MJ1998** [skydoves/PowerSpinner#49]
- Library Version : v 1.0.1

Description:
Java code i wrote to dismiss the spinner when touched outside: 
spinnerView.setOnSpinnerOutsideTouchListener((view, motionEvent) -> {
            spinnerView.dismiss();
            return null;
        });
this does not work

Expected Behaviour:
Spinner should dismiss when touched/swiped outside spinner view

**Comment by skydoves** [comment]
Hi, @MJ1998 
Try to use this code:
```java
spinner.setIsFocusable(true);
```

**Comment by skydoves** [comment]
I think this kind of issue are added frequently, so I will consider adding new attributes like `spinner_dismiss_touch_outside=true`

**Comment by MJ1998** [comment]
> Hi, @MJ1998
> Try to use this code:
> 
> ```java
> spinner.setIsFocusable(true);
> ```

still does not work. 
so basically i have 3 fragments implemented in view pager and the power spinner is in one of them. swiping outside spinner does not dismiss it.

**Comment by skydoves** [comment]
Hmm, that's weird. As you can build using the [demo](https://github.com/skydoves/PowerSpinner/blob/master/app/src/main/java/com/skydoves/powerspinnerdemo/MainActivity.kt#L40) project, the popup will be dismissed if you touch outside. I think there is an exceptional case in the Fragment. 🤔

**Comment by Elytum** [comment]
A temporary fix I'm using is adding an empty full-screen view to the activity's root in order to catch the outside clicks.
Any better idea ?

**Comment by skydoves** [comment]
Hi, @Elytum 
Isn't the below code works?
```kotlin
spinnerView.setIsFocusable(true)
```

**Comment by Elytum** [comment]
I tried it, but just like MJ1998, it didn't catch outside clicks. I'll investigate it later and give extra details it you want.

**Comment by skydoves** [comment]
@Elytum
If you can make an example repository, please share it :)
Thanks.

**Comment by skydoves** [comment]
Please re-open this issue if you face the same issue on the latest version.
Thanks :)
