### ISSUE TITLE
PowerSpinner height when updating the number of children

### ISSUE THREAD

**Issue by Elytum** [skydoves/PowerSpinner#53]
**Describe the Bug:**

When updating the recyclerview's children, added children are not showing up.
It appears that the recyclerview can only reduce it's size, therefore if you remove an item then add it back, it won't show up.
This is especially problematic in the case of permission-based buttons using PowerSpinner, where the spinner can be re-used with different entries, each offering different interactions.

**Expected Behavior:**

When adding or removing a child, let say a button for example, if there is space to show it, it should be shown.

**Comment by noumanshah-cb** [comment]
i am having the same issue any feedback on this

**Comment by shivamsoods** [comment]
I am also having the same issue. When there is a list of let's say 5 items and then I update the list and then it has 10 items, only 5 items are shown while rest 5 are scrollable. Even in it the scroll bars are not visible.

**Comment by M-Elnemr** [comment]
I was having the same issue and I figured out the solution.

you have to determine the spinnerPopupHeight at every time you update the recyclerview's children ,
for example 

spinner.setItems(itemList1)
spinner.spinnerPopupHeight = 75 * itemList1.size

// update the recyclerview's children
spinner.setItems(itemList2)
spinner.spinnerPopupHeight = 75 * itemList2.size

//update the recyclerview's children
spinner.setItems(itemList3)
spinner.spinnerPopupHeight = 75 * itemList3.size

/**75 is the item height ( I determined it after few tries  ) - so we multiply the item height with the items count*/

**Comment by skydoves** [comment]
Hi, sorry for the late reply.
A new version [1.2.0](https://github.com/skydoves/PowerSpinner/releases/tag/1.2.0) was released.
Now you can use the `spinner_popup_height` and `spinnerItemHeight` property for `PowerSpinnerView`.
By setting the attribute, the spinner will calculate the height size of the popup automatically whenever you call the `setItems` method. Thank you for reporting this issue!
