### ISSUE TITLE
Please add customfont option to spinner and list items

### ISSUE THREAD

**Issue by dasirahul7** [skydoves/PowerSpinner#55]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by aman-reso** [comment]
can i work on this?

**Comment by skydoves** [comment]
Sorry for the late reply.
The `IconSpinnerItem` receives `typeface: Int` as a parameter, but you mean  `Typeface` object for using custom fonts?

**Comment by skydoves** [comment]
@dasirahul7 @aman-reso 
On the `1.1.8-SNAPSHOT`, the previous `typeface` on the `IconSpinnerItem` class has been changed to `textStyle`.
And now we can use `textTypeface` parameter for applying custom font.
Thanks!

**Comment by csbenz** [comment]
This doesn't exist anymore, how can we set the typeface?
