### ISSUE TITLE
How to disable selected item background drawable from being set when invoked?

### ISSUE THREAD

**Issue by forceporquillo** [skydoves/PowerSpinner#56]
**Is your feature request related to a problem?**

Hello, I'd like to ask if how can I be able to prevent selected drawable from being set? for example, the flag in your sample let say the default flag I choose is USA, and whenever I change or select a different country from spinner the flag of USA still remains, and just ignore the invoked selected flags in the spinner.

Thank you!

**Comment by skydoves** [comment]
Hi, @forceporquillo 
Sorry for the late reply.
The sample uses `IconSpinnerAdapter` that implemented internally based on a [custom adapter](IconSpinnerAdapter).
And you can reference the internal code [IconSpinnerAdapter](https://github.com/skydoves/PowerSpinner/blob/master/powerspinner/src/main/java/com/skydoves/powerspinner/IconSpinnerAdapter.kt#L115), just change the `setCompoundDrawablesWithIntrinsicBounds` related codes on your custom adapter.
Thanks :)
