### ISSUE TITLE
Search bar with pop up dialog 

### ISSUE THREAD

**Issue by zainkhalid91** [skydoves/PowerSpinner#57]
Can we get a feature in which we can search from a list using search bar with pop up dialog. 
I have already implemented it but the code is too long and I have to implement 5,6 spinners in one screen which makes a lot of hassle for me.
e.g
In this feature if we have a list of countries we can search for the specific country by using search bar.

**Comment by skydoves** [comment]
Hi, sorry for the late response. For now, I don't have the search bar feature for this library. 
If I have any plans for this, I'll let you know about it via this issue. Thanks!
