### ISSUE TITLE
Error setOnSpinnerItemSelectedListener

### ISSUE THREAD

**Issue by brayann16** [skydoves/PowerSpinner#6]
- Library Version [1.0.4]
- Affected Device(s) [A51 Android 10]
 
**Describe the Bug:**
Here is my code in java:
 countrySpinner.setOnSpinnerItemSelectedListener(new OnSpinnerItemSelectedListener<String>() {
            @Override public void onItemSelected(int position, String item) {
                switch (countrySpinner.getSelectedIndex()){
                    case 1: visaTypeSpinner.setItems(R.array.Cuba);
                    case 2: visaTypeSpinner.setItems(R.array.Dubai);
                    default:;
                }
            }
        });

Here is the error i get when i compile
error: cannot access Function2
        countrySpinner.setOnSpinnerItemSelectedListener(new OnSpinnerItemSelectedListener<String>() {
                      ^
  class file for kotlin.jvm.functions.Function2 not found

**Comment by skydoves** [comment]
@brayann16 
Hi, I found some codes related to `setOnSpinnerItemSelectedListener` on [GitHub](https://github.com/Oblivious-Kibria/anc-prime/blob/ea7ec3b2f093c757ed114350886adcf3f2e6e178/app/src/main/java/com/anc/ancprime/views/activities/MainActivity.java#L292). It seems used with Java8 labmda expression, 
```gradle

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by brayann16** [comment]
What should I do to resolve this error ?

**Comment by skydoves** [comment]
I think the project just used kotlin plugin to resolve this error.

[build.gradle](https://github.com/Oblivious-Kibria/anc-prime/blob/master/build.gradle#L11)
[build.gradle-app](https://github.com/Oblivious-Kibria/anc-prime/blob/master/app/build.gradle#L2) line 2~3.
```gradle
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```

**Comment by brayann16** [comment]
It works, Thank you very much
