### ISSUE TITLE
How to set Corners for popup ?

### ISSUE THREAD

**Issue by gamalragab21** [skydoves/PowerSpinner#61]
How to set Raduis for Popup Background ?
or how to set spinner_popup_background to accept a drawable?

**Comment by skydoves** [comment]
Hi, @gamalragab21 
Could you show an example screenshot or design guide for the corner radius applied spinner?
I think it would look weird because the top selector is square generally..?

**Comment by malikbilal1997** [comment]
Also, need this feature.
