### ISSUE TITLE
The selection was made by the user. And spinner arrow is hidden.

### ISSUE THREAD

**Issue by sezginozgurr** [skydoves/PowerSpinner#62]
I want it not to be lost arrow.After the choice is made.
I want the arrow to remain open after the user has made a choice at the spinner.Can you help me please?

**Comment by skydoves** [comment]
Hi, could you explain more details about the hidden?
And is that occur the same issue in the [demo](https://github.com/skydoves/PowerSpinner/tree/master/app) project on your device?

**Comment by abhishektiwari-obsidiam** [comment]
@sezginozgurr You must be using IconSpinnerAdapter that's why.
