### ISSUE TITLE
No Callback when we click power spinner? And if no callback then at a time 2 power spinner open how we dismiss without callback?

### ISSUE THREAD

**Issue by bridgingamit18** [skydoves/PowerSpinner#63]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by bridgingamit18** [comment]
Just open first click without selecting item again we open second power spinner then how we close first if no callback request? Please guide

**Comment by skydoves** [comment]
Hi, sorry for the late response. You can achieve this with the codes below:

```kotlin
setOnSpinnerItemSelectedListener<String> { _, _, _, item ->
        binding.spinnerView2.hint = item
        Toast.makeText(applicationContext, item, Toast.LENGTH_SHORT).show()
      }
```

Thanks!
