### ISSUE TITLE
setOnSpinnerItemSelectedListener with adapter in java

### ISSUE THREAD

**Issue by binu8051** [skydoves/PowerSpinner#64]
Hi, i am using this spinner and my code is below

List<IconSpinnerItem> iconSpinnerItemss = new ArrayList<>();
iconSpinnerItemss.add(new IconSpinnerItem("View all", ContextCompat.getDrawable(getApplicationContext(), R.drawable.ic_map)));
iconSpinnerItemss.add(new IconSpinnerItem("Rock", ContextCompat.getDrawable(getApplicationContext(),  R.drawable.ic_map)));
iconSpinnerItemss.add(new IconSpinnerItem("Rocks", ContextCompat.getDrawable(getApplicationContext(),  R.drawable.ic_map)));
iconSpinnerItemss.add(new IconSpinnerItem("Rocks1", ContextCompat.getDrawable(getApplicationContext(),  R.drawable.ic_map)));
 iconSpinnerItemss.add(new IconSpinnerItem("Rocks2", ContextCompat.getDrawable(getApplicationContext(),  R.drawable.ic_map)));
 iconSpinnerItemss.add(new IconSpinnerItem("Rock3", ContextCompat.getDrawable(getApplicationContext(),  R.drawable.ic_map)));
        IconSpinnerAdapter iconSpinnerAdapters = new IconSpinnerAdapter(stonetype_viewdb);
        stonetype_viewdb.setSpinnerAdapter(iconSpinnerAdapters);
        stonetype_viewdb.setItems(iconSpinnerItemss);
        stonetype_viewdb.selectItemByIndex(0);
        stonetype_viewdb.setIsFocusable(true);
        stonetype_viewdb.setLifecycleOwner(this);

How to code for setOnSpinnerItemSelectedListener , while searching i found only kotlin code.
can anyone help to code it to get the position of selected item.
Thanks

**Comment by skydoves** [comment]
If you don't use a custom adapter, check the below codes.

```java
powerSpinnerView.setOnSpinnerItemSelectedListener(new OnSpinnerItemSelectedListener<String>() {
      @Override public void onItemSelected(int oldIndex, @Nullable String oldItem, int newIndex,
        String newItem) {

      }
    });
```

**Comment by binu8051** [comment]
i already tried this, but got this error.
`java.lang.ClassCastException: com.skydoves.powerspinner.IconSpinnerItem cannot be cast to java.lang.String`

**Comment by binu8051** [comment]
Hi, Any solution?

**Comment by skydoves** [comment]
As you can infer from the exception, replace String to `IconSpinnerItem`.
```java
powerSpinnerView.setOnSpinnerItemSelectedListener(new OnSpinnerItemSelectedListener<IconSpinnerItem>() {
      @Override
      public void onItemSelected(int oldIndex, @Nullable IconSpinnerItem oldItem, int newIndex,
        IconSpinnerItem newItem) {

      }
    });
```

**Comment by binu8051** [comment]
Thanks its worked.
Btw i cant set 
`app:spinner_popup_height="wrap_content"`
Getting error Cannot resolve symbol 'wrap_content'

**Comment by skydoves** [comment]
We can't use the `wrap_content`. It receives only the dimensional size like a `120dp`.
Thanks!
