### ISSUE TITLE
setting new items

### ISSUE THREAD

**Issue by KhaledSherifSayed** [skydoves/PowerSpinner#66]
**Please complete the following information:**
- Library-Version [e.g. v1.1.7]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

When setting New Items but size smaller than from list before the spinner crash in notifyItemSelected IndexOutOfBoundsException because this line 
"oldItem = oldIndex.takeIf { it != NO_SELECTED_INDEX }?.let { spinnerItems[oldIndex] }"

**Expected Behavior:**
set new items and setting old index to -1

**Comment by skydoves** [comment]
Released on a new version `1.1.8`.
