### ISSUE TITLE
Open dropdown to top

### ISSUE THREAD

**Issue by OPunktSchmidt** [skydoves/PowerSpinner#67]
I have a dropdown - spinner in my app, which is located at the bottom of the display. Because the dropdown always opens to the bottom, scrolling is difficult. It would be better if you could set the dropdown to open to the top. 

Is that currently already possible?

![Screenshot_20210621-190400](https://user-images.githubusercontent.com/7362709/122801318-3e904f80-d2c4-11eb-81d8-4bcda89c42cf.png)

**Comment by comradez** [comment]
I've got the same issues >_<
Hope this spinner can popup to top soon...

**Comment by ParryPatel021** [comment]
@skydoves Do we have any updates on this?

**Comment by skydoves** [comment]
Hi, sorry for the late reply. A new version [1.2.0](https://github.com/skydoves/PowerSpinner/releases/tag/1.2.0) was released.
Now you can use the `spinner_popup_height` and `spinnerItemHeight` property for `PowerSpinnerView`.
By setting the attribute, the spinner will calculate the height size of the popup automatically and it will shows the popup to the top if there is no more efficient space on the layout. Thank you!
