### ISSUE TITLE
Binding object to PowerSpinner.

### ISSUE THREAD

**Issue by lagger** [skydoves/PowerSpinner#69]
Hello. I need a little bit of help. I am trying to put object as an item to the powerspinner. I found that you should do this by creating ArrayAdapter etc. in normal spinner but it is not working here. How can I do this?

**Comment by skydoves** [comment]
Hi, You can implement it based on the [custom adapter](https://github.com/skydoves/PowerSpinner#customized-adapter-1) documentation.
Thanks!

**Comment by lagger** [comment]
Thanks for your response. I did it based on DefaultSpinnerAdapter but I don't know how to obtain bindingAdapterPosition and NO_SELECTED_INDEX value. Could you give me some advice?

**Comment by skydoves** [comment]
[IconSpinnerAdapter](https://github.com/skydoves/PowerSpinner/blob/master/powerspinner/src/main/java/com/skydoves/powerspinner/IconSpinnerAdapter.kt) is an example that you could reference. It receives `IconSpinnerItem`.
