### ISSUE TITLE
Question: How to clear a reset a selected value?

### ISSUE THREAD

**Issue by rashid56156** [skydoves/PowerSpinner#7]
Hello there,

So I was wondering is it possible to clear the spinner programmatically, resetting it back to default state with the only hint displayed?

Thanks,
Rashid.

**Comment by skydoves** [comment]
Hi, 
Yes, it is possible to clear the selected spinner text following this way.
```kotlin
notifyItemSelected(-1, "")
```
But it seems better to make a new API kind like `clear()` or `unSelect()` method.
Thank you for your issue :)
