### ISSUE TITLE
Height of adapter items not correct

### ISSUE THREAD

**Issue by shivamsoods** [skydoves/PowerSpinner#73]
- Library Version v1.1.8
- Affected Device(s) Redmi Note 5 Pro with Android 9.0
 
**Describe the Bug:**
The wrap_content of **app:spinner_popup_height** doesn't work properly when the item count of the list is changed. It takes the height of the smallest last used item list.

When there is a list of let's say 5 items, all the 5 items are displayed properly and then I update the list and also set the powerspinner and adpter agin and then the list has 10 items, only 5 items are shown while rest 5 are scrollable. Even in it the scroll bars are not visible.

**Expected Behavior:**
The wrap_content of the **app:spinner_popup_height** should change according to the size of the list and not the size of the previous smallest list.

**Comment by ubarua123** [comment]
In my case, one of the item's text was a little long, it appeared in one line in the item, but when you choose it, it appeared in 2 lines in the spinner display.
Then again you click on the spinner, the text flows out of the popup. 
Deal breaker for me.

**Comment by beniezsche** [comment]
@shivamsoods @ubarua123 any solution for this?

**Comment by skydoves** [comment]
#92
