### ISSUE TITLE
Custom View for Spinner

### ISSUE THREAD

**Issue by rtsketo** [skydoves/PowerSpinner#76]
**Is your feature request related to a problem?**

There's no option to set a custom view for the spinner.

**Describe the solution you'd like:**

PowerSpinnerView should be extending ConstraintLayout (or an other ViewGroup) instead of AppCompatTextView. That way it have the same view as the adapter below.

**Describe alternatives you've considered:**

As a workaround I placed a fake view above the spinner.

**Comment by skydoves** [comment]
Hi, I don't understand the meaning of the custom view for the spinner. 
You can change the spinner's drawable using this attribute.
```gradle
spinner_arrow_drawable
```
Custom view for spinner meaning that you need you to add some listeners or something on the spinner?

**Comment by rtsketo** [comment]
![customviewinspinner](https://user-images.githubusercontent.com/33037826/126040754-523d60db-a482-45f2-948f-4ae4e78d37a4.gif)

This is a custom view. Although not clearly visible, there are three TextViews and an ImageView. When you select an item, the selected view inside of the closed spinner has also the same layout as the ones in the dropdown menu. I think this option isn't available in the library.

**Comment by skydoves** [comment]
Gotcha. You can implement it using the [custom adapter](https://github.com/skydoves/powerspinner#customized-adapter).
Also, you can check [an example](https://github.com/skydoves/PowerSpinner/blob/master/powerspinner/src/main/java/com/skydoves/powerspinner/IconSpinnerAdapter.kt) for the custom adapter.

**Comment by rtsketo** [comment]
That's what I did! What you see in the GIF is my implementation of the custom adapter and it works great.
But... you don't have the option to have anything other than a String displayed after the selection is done.
In the example this `this.spinnerView.notifyItemSelected(index, item.text)` passes the String to the spinnerView to be displayed, correct?

Is it possible to have a `spinnerView` with a custom inner layout?

**Comment by skydoves** [comment]
Sorry for the late response. You can implement your own item layout, and custom notification functions in your custom adapter.  If you have further problems, please let me know. Thank you!
