### ISSUE TITLE
Custom Arrow Size

### ISSUE THREAD

**Issue by rtsketo** [skydoves/PowerSpinner#77]
**Is your feature request related to a problem?**

Arrow size can't be changed.

**Describe the solution you'd like:**

setArrowSize(px)

**Describe alternatives you've considered:**

None.

**Comment by skydoves** [comment]
duplicated: #72

**Comment by skydoves** [comment]
A new stable `1.1.9` has been released!
You can use the below method.

```kotlin
spinnerView.arrowSize = SpinnerArrowSizeSpec(width=60, height=60)
```
