### ISSUE TITLE
Arrow not showing when displaying images

### ISSUE THREAD

**Issue by ManchiGitHub** [skydoves/PowerSpinner#78]
**Please complete the following information:**
- Library Version: v1.1.8
- Affected Device(s): Samsung Tabs A with Android 10.0, TPS Tablet HG809A with Android 8.1.0
 
**Describe the Bug:**

Hi,
I am populating the spinner with text and a drawable for each row.
The spinner works fine except it doesn't show the arrow drawable.
'spinner_arrow_show' is set to true.

code snippet: 

        mSpinner = rootView.findViewById(R.id.country_spinner);

        List<IconSpinnerItem> iconSpinnerItems = new ArrayList<>();
        iconSpinnerItems.add(new IconSpinnerItem("Country1", getResources().getDrawable(R.drawable.rsz_country1)));
        iconSpinnerItems.add(new IconSpinnerItem("Country2", getResources().getDrawable(R.drawable.rsz_country2)));
        IconSpinnerAdapter iconSpinnerAdapter = new IconSpinnerAdapter(mSpinner);

        mSpinner.setSpinnerAdapter(iconSpinnerAdapter);
        mSpinner.setItems(iconSpinnerItems);
        mSpinner.selectItemByIndex(0);
        mSpinner.setLifecycleOwner(this);
        mSpinner.setShowArrow(true);

I've downloaded the demo app, which has a spinner with images, but without an arrow.

**Expected Behavior:**

The arrow should be displayed and animated according to the spinner state (closed and open).

**Comment by ParryPatel021** [comment]
@ManchiGitHub You can try to set tint color on the arrow.

` app:spinner_arrow_tint="#084F65"`

I think by default it is white.
