### ISSUE TITLE
error: cannot access Function2

### ISSUE THREAD

**Issue by AdilSattar1233** [skydoves/PowerSpinner#8]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy A01 with Android 10]
 
**Describe the Bug:**

On item selected not working

**Expected Behavior:**

error: cannot access Function2
                mBloodSpinner.setOnSpinnerItemSelectedListener(new OnSpinnerItemSelectedListener<Object>() {
                             ^

**Comment by MahmoudRashad** [comment]
I have the same issue 
error: cannot access Function2
        list.setOnSpinnerItemSelectedListener(new OnSpinnerItemSelectedListener<String>

**Comment by skydoves** [comment]
Hi, guys, It seems your projects are configured Java.
Please add kotlin plugins to your project.
[build.gradle](https://github.com/Oblivious-Kibria/anc-prime/blob/master/build.gradle#L11)
[build.gradle-app](https://github.com/Oblivious-Kibria/anc-prime/blob/master/app/build.gradle#L2) line 2~3.
```gradle
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```

**Comment by skydoves** [comment]
#6
