### ISSUE TITLE
PopupWindow shows in wrong places after onConfigurationChanged()

### ISSUE THREAD

**Issue by VolodymyrYeletskyi** [skydoves/PowerSpinner#81]
- Library Version - v1.1.9
- Affected Device(s): Samsung Galaxy A7, Samsung SM-J600F
 
**Describe the Bug:**
In my app I use 
`android:configChanges="orientation|screenSize"`
for activity in the manifest file, so when screen is rotate onConfigurationChanged method is called. 

`override fun onConfigurationChanged(newConfig: Configuration) {
        spinner.dismiss()
        super.onConfigurationChanged(newConfig)
    }`

After that PopupWindow shows not under the spinner and has a wrong size, and it looks creepy

**Expected Behavior:**
The PopupWindow should be displayed under the spinner with right size

**Comment by skydoves** [comment]
Hi, sorry for the late response.
For the configuration change, I highly recommend dismissing the popup and re-open when the layouts are inflated. 
Thanks!
