### ISSUE TITLE
Is it possible to set shape as popUpBackground?

### ISSUE THREAD

**Issue by Novikov** [skydoves/PowerSpinner#82]
When I try set popUpBackground using shape like that:
`        <com.skydoves.powerspinner.PowerSpinnerView
            android:id="@+id/spinner"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@drawable/background_alabaster_radius_10"
            android:padding="@dimen/grid_2"
            android:textAppearance="@style/Text.Default.Normal"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:spinner_arrow_show="false"
            app:spinner_divider_show="true"
            app:spinner_divider_size="0dp"
            app:spinner_popup_background="@drawable/background_primary_corner_10"
            android:hint="Hint"
            android:minHeight="50dp"
            android:textColorHint="@color/red"/>`

App crashes with exception:
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/background_primary_corner_10.xml from color state list resource ID #0x7f080061
        at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2750)
        at android.content.res.Resources.loadColorStateList(Resources.java:2699)
        at android.content.res.TypedArray.getColor(TypedArray.java:439)

**Comment by skydoves** [comment]
Hi, sorry for the late reply. A new version [1.2.0](https://github.com/skydoves/PowerSpinner/releases/tag/1.2.0) was released. Now you can set a drawable as a background with the `spinner_popup_background`. Thanks!
