### ISSUE TITLE
Disable dropdown

### ISSUE THREAD

**Issue by WenLonG12345** [skydoves/PowerSpinner#83]
Hi, I was happy to use this library but I have 1 feature that I cant find. 
Can I disable the spinner's dropdown? Which function should I use? 
Looking forward for any solution :)

**Comment by WenLonG12345** [comment]
I got myself an answer finally!
Just set the `PowerSpinnerView.isClickable = false` will disable the dropdown. 
Hope this helps someone! :)

**Comment by skydoves** [comment]
Great!
