### ISSUE TITLE
SpinnerView takes the smallest height of dynamic list when it changes

### ISSUE THREAD

**Issue by forceporquillo** [skydoves/PowerSpinner#86]
**Please complete the following information:**
- Library Version
   - v1.1.9
- Affected Device(s) 
   - Pixel 3 - Android 11
   - Samsung SMJ400G - Android 10
 
**Describe the Bug:**

I have a dynamic list where users can interactively choose what type of category they want. And every time a user changes a category, the height of the list should also interact with the new current height depending on the size of the list, not the smallest list height that was previously used.

**Expected Behavior:**

When setting new list items in the `SpinnerView` programmatically, it should invalidate and replace all old items with a new one in the `SpinnerAdapter` and take the maximum height between the new and the previous list. 

This issue is similar to #73 

Thanks!

**Comment by skydoves** [comment]
Hi, sorry for the late reply. A new version [1.2.0](https://github.com/skydoves/PowerSpinner/releases/tag/1.2.0) was released.
Now you can use the `spinner_popup_height` and `spinnerItemHeight` property for `PowerSpinnerView`.
By setting the attribute, the spinner will calculate the height size of the popup automatically whenever you call the `setItems` method. Thank you for reporting this issue!
