### ISSUE TITLE
How to change the color of selected text？

### ISSUE THREAD

**Issue by liuxuesong001** [skydoves/PowerSpinner#94]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
Hi @liuxuesong001,
You can achieve it with your own [custom adapter](https://github.com/skydoves/powerspinner#customized-adapter-1).
